services:
  pihole:
    image: pihole/pihole:2025.11.1
    container_name: pihole
    restart: unless-stopped
    # Use host networking for DNS (port 53)
    network_mode: host
    environment:
      - TZ=America/Sao_Paulo
      - FTLCONF_webserver_api_password=changeme
      # - FTLCONF_webserver_domain=pihole.yourdomain.com -- If you plan to have a custom domain for the web interface
      - FTLCONF_LOCAL_IPV4=127.0.0.1 # change me
      - FTLCONF_dns_upstreams=127.0.0.1#5335;127.0.0.1#5335
      - FTLCONF_webserver_port=8081 # change me optionally
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
  unbound:
    image: alpinelinux/unbound:latest
    container_name: unbound
    restart: unless-stopped
    # Share Pi-hole's network stack
    network_mode: service:pihole
    volumes:
      - ./unbound/unbound.conf:/etc/unbound/unbound.conf:ro
