services:
  pihole:
    image: pihole/pihole:2025.11.1
    container_name: pihole
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: ${TIMEZONE}
      FTLCONF_webserver_api_password: ${WEBPASSWORD}
      # FTLCONF_webserver_domain=pihole.yourdomain.com -- custom domain
      FTLCONF_LOCAL_IPV4: ${HOST_IPV4_ADDRESS} 
      FTLCONF_dns_upstreams: ${DNS_UPSTREAMS}
      FTLCONF_webserver_port: ${WEBPORT}
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
  unbound:
    image: alpinelinux/unbound:latest
    container_name: unbound
    restart: unless-stopped
    network_mode: service:pihole
    volumes:
      - ./unbound/unbound.conf:/etc/unbound/unbound.conf:ro
